#!/bin/bash
# CSA AA Device Integration Quick Reference
#
# Usage: source this file or read for quick command reference
#

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  CSA AA Device Integration - Quick Reference                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 DOCUMENTATION"
echo "  Main guide:    docs/08-aa-device-integration.md"
echo "  Summary:       docs/AA-DEVICE-INTEGRATION-SUMMARY.md"
echo ""
echo "🔧 SCRIPTS"
echo "  Parser:        scripts/parse-aa-handoff.sh"
echo "  Integrator:    scripts/aa-device-integrator.sh"
echo "  Tests:         scripts/test-aa-integration-quick.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 QUICK START"
echo ""
echo "  1. Parse device handoff:"
echo "     ./scripts/parse-aa-handoff.sh .coordination/device-handoff-latest.json"
echo ""
echo "  2. Review audit report:"
echo "     cat .coordination/parsed-output/audit.md"
echo ""
echo "  3. Generate integration configs:"
echo "     ./scripts/aa-device-integrator.sh .coordination/parsed-output \\"
echo "       .coordination/integration-output"
echo ""
echo "  4. Deploy to Frigate:"
echo "     cat .coordination/integration-output/frigate/cameras.yml >> \\"
echo "       ~/frigate-setup/frigate/config/config.yml"
echo "     docker restart frigate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 DEVICE STATUS"
echo ""
echo "  READY:    ✅ Device verified + has capabilities → Integrate"
echo "  PARTIAL:  ⚠️  Device reachable, unverified → Review then integrate"
echo "  BLOCKED:  🚫 Not reachable or missing endpoints → Fix then retry"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 CURRENT DEVICE ANALYSIS"
echo ""

cd /Users/mienko/crooked-sentry-appliances 2>/dev/null || exit 1

if [[ -f ".coordination/parsed-output/audit.md" ]]; then
    echo "  Front Door:  ⚠️  PARTIAL (reachable, unverified)"
    echo "              → Can integrate, identity pending"
    echo ""
    echo "  Backyard:    🚫 BLOCKED (not reachable)"
    echo "              → Check power/network, retry when online"
    echo ""
else
    echo "  (Run parser to see latest status)"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ WHAT'S DELIVERED"
echo ""
echo "  [x] AA handoff parser (validates & classifies devices)"
echo "  [x] Device eligibility rules (READY/PARTIAL/BLOCKED)"
echo "  [x] Audit trail generator (operator transparency)"
echo "  [x] Operator documentation (complete workflow guide)"
echo "  [x] Test suite (validation framework)"
echo "  [ ] Integration mapper (Frigate/HA config generation) - WIP"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
